/*
 * generated by Xtext 2.13.0
 */
package org.xtext.example.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.parser.antlr.internal.InternalSimulinkParser;
import org.xtext.example.services.SimulinkGrammarAccess;

public class SimulinkParser extends AbstractAntlrParser {

	@Inject
	private SimulinkGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSimulinkParser createParser(XtextTokenStream stream) {
		return new InternalSimulinkParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Root";
	}

	public SimulinkGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SimulinkGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
