/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example;

import org.xtext.example.AbstractSimulinkRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SimulinkRuntimeModule extends AbstractSimulinkRuntimeModule {
}
