/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example;

import org.xtext.example.SimulinkStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SimulinkStandaloneSetup extends SimulinkStandaloneSetupGenerated {
  public static void doSetup() {
    new SimulinkStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
