/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.ide;

import org.xtext.example.ide.AbstractSimulinkIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class SimulinkIdeModule extends AbstractSimulinkIdeModule {
}
