/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.SimulinkRuntimeModule;
import org.xtext.example.SimulinkStandaloneSetup;
import org.xtext.example.ide.SimulinkIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class SimulinkIdeSetup extends SimulinkStandaloneSetup {
  @Override
  public Injector createInjector() {
    SimulinkRuntimeModule _simulinkRuntimeModule = new SimulinkRuntimeModule();
    SimulinkIdeModule _simulinkIdeModule = new SimulinkIdeModule();
    return Guice.createInjector(Modules2.mixin(_simulinkRuntimeModule, _simulinkIdeModule));
  }
}
