/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.validation;

import org.xtext.example.validation.AbstractSimulinkValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SimulinkValidator extends AbstractSimulinkValidator {
}
