/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.simulink;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Matrix Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.simulink.MatrixElement#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.simulink.SimulinkPackage#getMatrixElement()
 * @model
 * @generated
 */
public interface MatrixElement extends Element
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute list.
   * @see org.xtext.example.simulink.SimulinkPackage#getMatrixElement_Value()
   * @model unique="false"
   * @generated
   */
  EList<String> getValue();

} // MatrixElement
