/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.simulink;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.simulink.SimulinkFactory
 * @model kind="package"
 * @generated
 */
public interface SimulinkPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "simulink";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl1/Simulink";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "simulink";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SimulinkPackage eINSTANCE = org.xtext.example.simulink.impl.SimulinkPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.simulink.impl.RootImpl <em>Root</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.simulink.impl.RootImpl
   * @see org.xtext.example.simulink.impl.SimulinkPackageImpl#getRoot()
   * @generated
   */
  int ROOT = 0;

  /**
   * The feature id for the '<em><b>Root Element</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOT__ROOT_ELEMENT = 0;

  /**
   * The number of structural features of the '<em>Root</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.simulink.impl.ElementImpl <em>Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.simulink.impl.ElementImpl
   * @see org.xtext.example.simulink.impl.SimulinkPackageImpl#getElement()
   * @generated
   */
  int ELEMENT = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.simulink.impl.SubElementImpl <em>Sub Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.simulink.impl.SubElementImpl
   * @see org.xtext.example.simulink.impl.SimulinkPackageImpl#getSubElement()
   * @generated
   */
  int SUB_ELEMENT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_ELEMENT__NAME = ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Element</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_ELEMENT__ELEMENT = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Sub Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_ELEMENT_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.simulink.impl.BaseElementImpl <em>Base Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.simulink.impl.BaseElementImpl
   * @see org.xtext.example.simulink.impl.SimulinkPackageImpl#getBaseElement()
   * @generated
   */
  int BASE_ELEMENT = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BASE_ELEMENT__NAME = ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BASE_ELEMENT__VALUE = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Base Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BASE_ELEMENT_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.simulink.impl.VectorElementImpl <em>Vector Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.simulink.impl.VectorElementImpl
   * @see org.xtext.example.simulink.impl.SimulinkPackageImpl#getVectorElement()
   * @generated
   */
  int VECTOR_ELEMENT = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VECTOR_ELEMENT__NAME = ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VECTOR_ELEMENT__VALUE = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Vector Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VECTOR_ELEMENT_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.simulink.impl.MatrixElementImpl <em>Matrix Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.simulink.impl.MatrixElementImpl
   * @see org.xtext.example.simulink.impl.SimulinkPackageImpl#getMatrixElement()
   * @generated
   */
  int MATRIX_ELEMENT = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MATRIX_ELEMENT__NAME = ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MATRIX_ELEMENT__VALUE = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Matrix Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MATRIX_ELEMENT_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.simulink.impl.StringElementImpl <em>String Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.simulink.impl.StringElementImpl
   * @see org.xtext.example.simulink.impl.SimulinkPackageImpl#getStringElement()
   * @generated
   */
  int STRING_ELEMENT = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_ELEMENT__NAME = ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_ELEMENT__VALUE = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>String Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_ELEMENT_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.simulink.Root <em>Root</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Root</em>'.
   * @see org.xtext.example.simulink.Root
   * @generated
   */
  EClass getRoot();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.simulink.Root#getRootElement <em>Root Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Root Element</em>'.
   * @see org.xtext.example.simulink.Root#getRootElement()
   * @see #getRoot()
   * @generated
   */
  EReference getRoot_RootElement();

  /**
   * Returns the meta object for class '{@link org.xtext.example.simulink.SubElement <em>Sub Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sub Element</em>'.
   * @see org.xtext.example.simulink.SubElement
   * @generated
   */
  EClass getSubElement();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.simulink.SubElement#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Element</em>'.
   * @see org.xtext.example.simulink.SubElement#getElement()
   * @see #getSubElement()
   * @generated
   */
  EReference getSubElement_Element();

  /**
   * Returns the meta object for class '{@link org.xtext.example.simulink.Element <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element</em>'.
   * @see org.xtext.example.simulink.Element
   * @generated
   */
  EClass getElement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.simulink.Element#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.simulink.Element#getName()
   * @see #getElement()
   * @generated
   */
  EAttribute getElement_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.simulink.BaseElement <em>Base Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Base Element</em>'.
   * @see org.xtext.example.simulink.BaseElement
   * @generated
   */
  EClass getBaseElement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.simulink.BaseElement#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.simulink.BaseElement#getValue()
   * @see #getBaseElement()
   * @generated
   */
  EAttribute getBaseElement_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.simulink.VectorElement <em>Vector Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Vector Element</em>'.
   * @see org.xtext.example.simulink.VectorElement
   * @generated
   */
  EClass getVectorElement();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.simulink.VectorElement#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Value</em>'.
   * @see org.xtext.example.simulink.VectorElement#getValue()
   * @see #getVectorElement()
   * @generated
   */
  EAttribute getVectorElement_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.simulink.MatrixElement <em>Matrix Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Matrix Element</em>'.
   * @see org.xtext.example.simulink.MatrixElement
   * @generated
   */
  EClass getMatrixElement();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.simulink.MatrixElement#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Value</em>'.
   * @see org.xtext.example.simulink.MatrixElement#getValue()
   * @see #getMatrixElement()
   * @generated
   */
  EAttribute getMatrixElement_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.simulink.StringElement <em>String Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Element</em>'.
   * @see org.xtext.example.simulink.StringElement
   * @generated
   */
  EClass getStringElement();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.simulink.StringElement#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Value</em>'.
   * @see org.xtext.example.simulink.StringElement#getValue()
   * @see #getStringElement()
   * @generated
   */
  EAttribute getStringElement_Value();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SimulinkFactory getSimulinkFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.simulink.impl.RootImpl <em>Root</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.simulink.impl.RootImpl
     * @see org.xtext.example.simulink.impl.SimulinkPackageImpl#getRoot()
     * @generated
     */
    EClass ROOT = eINSTANCE.getRoot();

    /**
     * The meta object literal for the '<em><b>Root Element</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROOT__ROOT_ELEMENT = eINSTANCE.getRoot_RootElement();

    /**
     * The meta object literal for the '{@link org.xtext.example.simulink.impl.SubElementImpl <em>Sub Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.simulink.impl.SubElementImpl
     * @see org.xtext.example.simulink.impl.SimulinkPackageImpl#getSubElement()
     * @generated
     */
    EClass SUB_ELEMENT = eINSTANCE.getSubElement();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUB_ELEMENT__ELEMENT = eINSTANCE.getSubElement_Element();

    /**
     * The meta object literal for the '{@link org.xtext.example.simulink.impl.ElementImpl <em>Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.simulink.impl.ElementImpl
     * @see org.xtext.example.simulink.impl.SimulinkPackageImpl#getElement()
     * @generated
     */
    EClass ELEMENT = eINSTANCE.getElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEMENT__NAME = eINSTANCE.getElement_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.simulink.impl.BaseElementImpl <em>Base Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.simulink.impl.BaseElementImpl
     * @see org.xtext.example.simulink.impl.SimulinkPackageImpl#getBaseElement()
     * @generated
     */
    EClass BASE_ELEMENT = eINSTANCE.getBaseElement();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BASE_ELEMENT__VALUE = eINSTANCE.getBaseElement_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.simulink.impl.VectorElementImpl <em>Vector Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.simulink.impl.VectorElementImpl
     * @see org.xtext.example.simulink.impl.SimulinkPackageImpl#getVectorElement()
     * @generated
     */
    EClass VECTOR_ELEMENT = eINSTANCE.getVectorElement();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VECTOR_ELEMENT__VALUE = eINSTANCE.getVectorElement_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.simulink.impl.MatrixElementImpl <em>Matrix Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.simulink.impl.MatrixElementImpl
     * @see org.xtext.example.simulink.impl.SimulinkPackageImpl#getMatrixElement()
     * @generated
     */
    EClass MATRIX_ELEMENT = eINSTANCE.getMatrixElement();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MATRIX_ELEMENT__VALUE = eINSTANCE.getMatrixElement_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.simulink.impl.StringElementImpl <em>String Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.simulink.impl.StringElementImpl
     * @see org.xtext.example.simulink.impl.SimulinkPackageImpl#getStringElement()
     * @generated
     */
    EClass STRING_ELEMENT = eINSTANCE.getStringElement();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_ELEMENT__VALUE = eINSTANCE.getStringElement_Value();

  }

} //SimulinkPackage
