/*
 * generated by Xtext 2.13.0
 */
package org.xtext.example


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SimulinkStandaloneSetup extends SimulinkStandaloneSetupGenerated {

	def static void doSetup() {
		new SimulinkStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
