/*
 * generated by Xtext 2.13.0
 */
package org.xtext.example.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.converter.simulink.ui.internal.SimulinkActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SimulinkExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(SimulinkActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		SimulinkActivator activator = SimulinkActivator.getInstance();
		return activator != null ? activator.getInjector(SimulinkActivator.ORG_XTEXT_EXAMPLE_SIMULINK) : null;
	}

}
