/*
 * generated by Xtext 2.13.0
 */
package org.xtext.example.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSimulinkScopeProvider extends DelegatingScopeProvider {
}
